
# 第一阶段
FROM swr.cn-southwest-2.myhuaweicloud.com/llody/python:3.9.10-slim as builder
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt -i https://mirrors.aliyun.com/pypi/simple/

# 第二阶段
FROM swr.cn-southwest-2.myhuaweicloud.com/llody/python:3.9.10-slim
LABEL maintainer="llody"
COPY --from=builder /usr/local/lib/python3.9 /usr/local/lib/python3.9
WORKDIR /app
COPY . .
CMD ["python", "app.py"]

