---
apiVersion: v1
kind: Namespace
metadata:
  name: podwatchers
---
# ServiceAccount
apiVersion: v1
kind: ServiceAccount
metadata:
  name: podwatchers
  namespace: podwatchers
---
# ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podwatchers
rules:
- apiGroups: [""]
  resources: ["pods", "events", "nodes"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["pods/log"]
  verbs: ["get"]
- apiGroups: [""]
  resources: ["pods/status"]
  verbs: ["update"]
---
# ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podwatchers
subjects:
- kind: ServiceAccount
  name: podwatchers
  namespace: podwatchers
roleRef:
  kind: ClusterRole
  name: podwatchers
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Secret
metadata:
  name: podwatchers-secrets
  namespace: podwatchers
type: Opaque
stringData:
  WEBHOOK_URL: "https://qyapi.weixin.qq.com/cgi-bin/webhook/send?key="  
  CLUSTER_NAME: "prod-cluster"  
  MUTE_SECONDS: "600"  
  IGNORE_RESTART_COUNT: "1"
  LOG_LINES: "200"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: podwatchers
  namespace: podwatchers
spec:
  replicas: 1
  selector:
    matchLabels:
      app: podwatchers
  template:
    metadata:
      labels:
        app: podwatchers
    spec:
      serviceAccountName: podwatchers
      containers:
      - name: collector
        image: swr.cn-southwest-2.myhuaweicloud.com/llody/podwatchers:v1.0-amd64
        imagePullPolicy: Always
        env:
        - name: CLUSTER_NAME
          valueFrom:
            secretKeyRef:
              name: podwatchers-secrets
              key: CLUSTER_NAME
        - name: WEBHOOK_URL
          valueFrom:
            secretKeyRef:
              name: podwatchers-secrets
              key: WEBHOOK_URL
        - name: MUTE_SECONDS
          valueFrom:
            secretKeyRef:
              name: podwatchers-secrets
              key: MUTE_SECONDS
        - name: IGNORE_RESTART_COUNT
          valueFrom:
            secretKeyRef:
              name: podwatchers-secrets
              key: IGNORE_RESTART_COUNT
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
